<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4oxvxh2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4oxvxh2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4oxvxh2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4oxvxh2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4oxvxh2\App_KernelDevDebugContainer([
    'container.build_hash' => '4oxvxh2',
    'container.build_id' => '5727fe85',
    'container.build_time' => 1667225747,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4oxvxh2');
