<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPK6R3Ba\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPK6R3Ba/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPK6R3Ba.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPK6R3Ba\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPK6R3Ba\App_KernelDevDebugContainer([
    'container.build_hash' => 'PK6R3Ba',
    'container.build_id' => 'ec272dc9',
    'container.build_time' => 1667209773,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPK6R3Ba');
