<?php

namespace ContainerPK6R3Ba;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bfl_F9FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bfl.F9F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bfl.F9F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'author' => ['privates', '.errored..service_locator.bfl.F9F.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.bfl.F9F": it references class "App\\Entity\\Author" but no such service exists.'],
        ], [
            'author' => 'App\\Entity\\Author',
        ]);
    }
}
